name: ilmart
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.11
  - tqdm==4.65.0
  - matplotlib
  - optuna==3.5.0
  - pip==23.3.1
  - interpret==0.5.1
  - boost==1.82.0
  - boost-cpp==1.82.0
  - libboost==1.82.0
  - py-boost==1.82.0
  -
  - pip:
    - Cython==3.0.8
    - tensorflow-ranking==0.5.0
    - tensorflow-datasets==4.9.4
    - pygam==0.9.1
    - joblib==1.3.2
    # - tensorflow==2.15.0 to be installed separately to avoid conflicts with tensorflow-ranking